#define buffer1 "################\n"
#define buffer2 "-----------------------------------\n"
#define main_Menu "Choose Your case:\n"
#define menu_Option1 "(1 = Add friend)\n"
#define menu_Option2 "(2 = Add fanpag)\n"
#define menu_Option3 "(3 = Add status to friend or fanpage)\n"
#define menu_Option4 "(4 = Show all the statuses of a friend or fanpage)\n"
#define menu_Option5 "(5 = Show the last 10 statuses of a friends of a particular friend)\n"
#define menu_Option6 "(6 = Show all entities registered to the system)\n"
#define menu_Option7 "(7 = Link between 2 friends)\n"
#define menu_Option8 "(8 = Cancle friendship between 2 friends)\n"
#define menu_Option9 "(9 = Link friend with fanpage)\n"
#define menu_Option10 "(10 = Cancle link friend with fanpage)\n"
#define menu_Option11 "(11 = Show all the friends of a particular friend or fanpage)\n"
#define menu_Option12 "(12 = Exit)\n"
#define enter_Friends_Name "Enter friend's name: "
#define enter_Friends_Birth_Date "Enter friend's birth date:\n"
#define enter_Fan_Pages_Name "Enter FanPage's name: "
#define add_Status_To_Friend_Or_Fan_Page "Add status to friend (1) or fanpage (2)? "
#define enter_Statuses_Publish_Date "Enter status's publish date:\n"
#define enter_ID_Of_The_Writer_Friend "Enter the ID of the writer of the status from among the existing friends: \n"
#define enter_the_content_of_the_status "Enter the content of the status:"
#define enter_ID_Of_The_Writer_Fan_Page "Enter the serial number of the writer of the status from among the existing fanpages: \n"
#define invalid_Option "This is not a valid option!\n"
#define show_Status_of_Friend_Or_Fan_Page "Show statuses of friend (1) or fanpage (2)? "
#define enter_The_ID_Of_The_Friend_Who_You_Want_To_See_His_Wall "Enter the ID of the friend who you want to see his wall: \n"
#define enter_The_ID_Of_The_First_Friend "Enter the ID of the first friend:\n"
#define enter_The_ID_Of_The_Friend_You_Want_To_Link "Enter the ID of the friend you want to link:\n"
#define enter_The_ID_Of_The_Friend_You_Want_To_Unlink "Enter the serial number of the friend you want to remove friendship from:\n"
#define Friend_Is_Fan_Of_All_The_FanPages "This friend is fan of all the fanpages!\n"
#define enter_The_ID_Of_The_FanPage_To_Link "Enter the ID of the FanPage you want to link:\n"
#define enter_The_ID_Of_The_Friend "Enter the ID of the friend:\n"
#define  friend_Has_No_FanPages "This Friend has no fanpages!\n"
#define enter_The_ID_Of_The_FanPage_To_Unlink "Enter the ID of the FanPage you want to Unlink:\n"
#define have_A_Nice_Day "Have a nice day! :)\n"
#define enter_Day "Enter day: "
#define day_Error_Value "Day must be a value between 1 and 31!\n"
#define enter_Month "Enter month: "
#define month_Error_Value "Month must be a value between 1 and 12!\n"
#define enter_Year "Enter year: "
#define year_Error_Value "Year must be a value between 1900 and 2023!\n"
#define enter_Hour "Enter hour: "
#define hour_Error_Value "Hour must be a value between 0 and 23!\n";
#define enter_Minute "Enter minute: "
#define minute_Error_Value "Minute must be a value between 0 and 59!\n";
#define ID_Not_Valid "This ID is not valid!\n";
#define Friends_Already_linked "This two friends are already linked!\n";
#define Cannot_Link_Friend_To_Himself "Cannot Link the same friend to himself!\n";
#define Friend_ID_Doesnt_Exist "Friend ID Doesn't Exist!\n";
#define Friend_1_ID_Doesnt_Exist "Friend 1 ID Doesn't Exist!\n";
#define Friend_2_ID_Doesnt_Exist "Friend 2 ID Doesn't Exist!\n";
#define FanPage_ID_Doesnt_Exist "Fanpage ID Doesn't Exist!\n";
#define This_Friends_Are_Not_Friends "These two friends are not each other's friends at all!\n"
#define Friend_1_Is_Friend_With_All_The_Friends_On_Facebook "Friend 1 is friend with all the friends on facebook!\n"
#define Friend_2_Is_Friend_With_All_The_Friends_On_Facebook "Friend 2 is friend with all the friends on facebook!\n"
#define Friend_1_Has_No_Friends_At_All "Friend 1 has no friends al all!\n"
#define Friend_2_Has_No_Friends_At_All "Friend 2 has no friends al all!\n"
#define Friend_And_FanPage_Already_Linked "This friend and fanpage are already linked!\n"
#define Friend_And_FanPage_Not_Linked "This friend and fan page are not linked to each other!\n"
#define Enter_The_ID_Of_The_Friend_Or_Fanpage_To_See_His_Friends_List "Enter the ID of the friend or fanpage who you want to see his/her friends list:\n"
#define press_1_To_Go_Back_To_Main_Menu "(Press 1 to go back to main menu)\n";